name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v2

    - name: Add GitHub Registry
      run: dotnet nuget add source --username carsten-computer-club --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/carsten-computer-club/index.json"

    - name: Build
      run: dotnet build -c Release

    - name: Publish
      run: dotnet publish -c Release -o build -r linux-arm -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true src/JAIS/JAIS.csproj;

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Jais-CI-Build
        path: build/JAIS
